"""initial_schema

Revision ID: 0111dc35be4e
Revises: 
Create Date: 2026-09-10 05:00:58.874821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0111dc35be4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('accent', sa.String(length=7), nullable=False),
    sa.Column('public_portal', sa.Boolean(), nullable=False),
    sa.Column('email_alerts', sa.Boolean(), nullable=False),
    sa.Column('sla_hours', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=30), nullable=False),
    sa.Column('point_limit', sa.Integer(), nullable=False),
    sa.Column('logo_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company')),
    sa.UniqueConstraint('slug', name=op.f('uq_company_slug'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('auth_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_location_company_id_company')),
    sa.ForeignKeyConstraint(['parent_id'], ['location.id'], name=op.f('fk_location_parent_id_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location'))
    )
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_company_id'), ['company_id'], unique=False)

    op.create_table('membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('specialty', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_membership_company_id_company')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_membership_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_membership')),
    sa.UniqueConstraint('company_id', 'email', name=op.f('uq_membership_company_id'))
    )
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_membership_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_membership_user_id'), ['user_id'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('send_email', sa.Boolean(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_notification_company_id_company')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_notification_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_notification_dedupe_key'))
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('password_reset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_password_reset_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_reset_token_hash'))
    )
    op.create_table('invitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['membership_id'], ['membership.id'], name=op.f('fk_invitation_membership_id_membership')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitation')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_invitation_token_hash'))
    )
    op.create_table('qr_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_qr_point_company_id_company')),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_qr_point_location_id_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qr_point')),
    sa.UniqueConstraint('code', name=op.f('uq_qr_point_code'))
    )
    with op.batch_alter_table('qr_point', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qr_point_company_id'), ['company_id'], unique=False)

    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=24), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('submit_key', sa.String(length=64), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('rating IS NULL OR (rating >= 1 AND rating <= 5)', name=op.f('ck_ticket_rating_range')),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_ticket_company_id_company')),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_ticket_location_id_location')),
    sa.ForeignKeyConstraint(['provider_id'], ['membership.id'], name=op.f('fk_ticket_provider_id_membership')),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], name=op.f('fk_ticket_requester_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket')),
    sa.UniqueConstraint('reference', name=op.f('uq_ticket_reference')),
    sa.UniqueConstraint('submit_key', name=op.f('uq_ticket_submit_key'))
    )
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_status'), ['status'], unique=False)

    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('membership_id', sa.Integer(), nullable=True),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('storage_name', sa.String(length=80), nullable=False),
    sa.Column('mime', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_attachment_company_id_company')),
    sa.ForeignKeyConstraint(['membership_id'], ['membership.id'], name=op.f('fk_attachment_membership_id_membership')),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], name=op.f('fk_attachment_ticket_id_ticket')),
    sa.ForeignKeyConstraint(['uploader_id'], ['user.id'], name=op.f('fk_attachment_uploader_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachment')),
    sa.UniqueConstraint('storage_name', name=op.f('uq_attachment_storage_name'))
    )
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachment_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachment_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], name=op.f('fk_event_actor_id_user')),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_event_company_id_company')),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], name=op.f('fk_event_ticket_id_ticket')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event'))
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_ticket_id'), ['ticket_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_event_company_id'))

    op.drop_table('event')
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachment_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_attachment_company_id'))

    op.drop_table('attachment')
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_status'))
        batch_op.drop_index(batch_op.f('ix_ticket_requester_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_provider_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_company_id'))

    op.drop_table('ticket')
    with op.batch_alter_table('qr_point', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qr_point_company_id'))

    op.drop_table('qr_point')
    op.drop_table('invitation')
    op.drop_table('password_reset')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_company_id'))

    op.drop_table('notification')
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_membership_user_id'))
        batch_op.drop_index(batch_op.f('ix_membership_company_id'))

    op.drop_table('membership')
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_company_id'))

    op.drop_table('location')
    op.drop_table('user')
    op.drop_table('company')
    # ### end Alembic commands ###
